FROM java:8
MAINTAINER anurak Th.
EXPOSE 8888
ADD  bookstore-0.0.1-SNAPSHOT.jar /home/bookstore-0.0.1-SNAPSHOT.jar
CMD ["/usr/lib/jvm/java-8-openjdk-amd64/bin/java", "-jar", "/home/bookstore-0.0.1-SNAPSHOT.jar"]